### ISSUE TITLE
template file generates invalid .table file

### ISSUE THREAD

**Issue by g051051** [dirigiblelabs/template-database-table#1]
**Describe the bug**
The .table file created from the template is invalid, due to using single quotes instead of double quotes.

**To Reproduce**
1. Go to 'Welcome Page'
2. Click on 'template-database-table/template.js'
3. Fill in required fields and click "Generate".
4. Open the resulting file in the table editor.
5. The file is corrupt...the Table Description just says {{file}}, and the file can't be edited.
6. Close the file, then reopen in the Monaco editor.  The editor will highlight each field and show an error "Property keys must be doublequoted".

**Expected behavior**
The file opens correctly in the table editor and is editable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88

**Additional context**
Manually editing the resulting file to replace the single quotes with double quotes fixes the error and allows the file to be edited correctly.

**Comment by ThuF** [comment]
Fixed with PR: https://github.com/dirigiblelabs/template-database-table/pull/2
